// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7KvsKvE-A7wiB6MiSWXYRy_JNL1L_txk',
    appId: '1:37225268474:web:26e50c9120c418ce4c7543',
    messagingSenderId: '37225268474',
    projectId: 'phone-verify-bloc',
    authDomain: 'phone-verify-bloc.firebaseapp.com',
    storageBucket: 'phone-verify-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi__HUptPc_BAjpJs5Rf6ya4aI95kQkpM',
    appId: '1:37225268474:android:58acf02a11c182374c7543',
    messagingSenderId: '37225268474',
    projectId: 'phone-verify-bloc',
    storageBucket: 'phone-verify-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaolC6aFLCHAP09s65_pRXXpewzrNeyc',
    appId: '1:37225268474:ios:8884792bbdec1fe84c7543',
    messagingSenderId: '37225268474',
    projectId: 'phone-verify-bloc',
    storageBucket: 'phone-verify-bloc.appspot.com',
    iosClientId: '37225268474-n8iv68oiem73bh9hmfp438qpn3he5i3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGaolC6aFLCHAP09s65_pRXXpewzrNeyc',
    appId: '1:37225268474:ios:8884792bbdec1fe84c7543',
    messagingSenderId: '37225268474',
    projectId: 'phone-verify-bloc',
    storageBucket: 'phone-verify-bloc.appspot.com',
    iosClientId: '37225268474-n8iv68oiem73bh9hmfp438qpn3he5i3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthBloc',
  );
}
